name: project310
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.2
  json_serializable: any
  json_annotation: ^4.5.0
  shared_preferences: ^2.0.15
  provider: ^6.0.2
  email_validator: ^2.0.1
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  image_picker: ^0.8.5+3
  firebase_analytics: ^9.1.9
  firebase_crashlytics: ^2.8.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  google_sign_in: ^5.3.2
  video_player: ^2.2.19
  photo_view: ^0.14.0
  video_thumbnail: ^0.5.0
  path_provider: ^2.0.11
  chewie: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/SUConnect-logos_transparent.png
    - assets/google_logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
