// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS71DO0FxZQ1XobbXp6H8OQ35Ylhw4sr8',
    appId: '1:322834229416:android:d9123031f902fbdc9cfa9d',
    messagingSenderId: '322834229416',
    projectId: 'project310-9fc0a',
    databaseURL: 'https://project310-9fc0a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project310-9fc0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3-O4vwQUX3c8ZYSOHrlfHW99dYPPrT4',
    appId: '1:322834229416:ios:c54cb2c46e3881769cfa9d',
    messagingSenderId: '322834229416',
    projectId: 'project310-9fc0a',
    databaseURL: 'https://project310-9fc0a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project310-9fc0a.appspot.com',
    iosClientId: '322834229416-r0t33qvgujv0gr56urg9iucj118cj6ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.project310',
  );
}
